AutoGrader/AutoGrader/Controllers/AssignmentController.cs
using System.Threading.Tasks;
using AutoGrader.DataAccess;
using AutoGrader.Models.Assignment;
using AutoGrader.Models.Submission;
using AutoGrader.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using ShellHelper;
using AutoGrader.Methods.GraderMethod;
using AutoGrader.Models;
using AutoGrader.DataAccess.Services.ClassServices;
using System.Collections.Generic;
using System;
using System.Linq;
using AutoGrader.Models.Users;
using AutoGrader.DataAccess.Services;
using Microsoft.AspNetCore.Identity;

namespace AutoGrader.Controllers
{
    public class AssignmentController : Controller
    {
        private AutoGraderDbContext dbContext;
        private UserManager<IdentityUser> UserManager;
        private Student student;

        public AssignmentController(AutoGraderDbContext dbContext, UserManager<IdentityUser> userManager)
        {
            this.dbContext = dbContext;
            this.UserManager = userManager;
        }

        public IActionResult CreateAssignment(int Id)
        {
            AssignmentViewModel model = new AssignmentViewModel()
            {
                ClassId = Id
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAssignment(AssignmentViewModel model)
        {
            if (ModelState.IsValid)
            {
                Assignment assignment = new Assignment(model);
                AssignmentDataService assignmentDataService = new AssignmentDataService(dbContext);
                assignmentDataService.AddAssignment(assignment);

                ClassDataService classDataService = new ClassDataService(dbContext);
                Class c = classDataService.GetClassById(assignment.ClassId);
                c.Assignments.Add(assignment);
            }

            await dbContext.SaveChangesAsync();

            return RedirectToAction("Index", "Home");
        }

        public IActionResult AddExistingAssignment(int classId, int instructorId)
        {
            AssignmentDataService assignmentDataService = new AssignmentDataService(dbContext);
            var assignments = assignmentDataService.GetAssignmentsByInstructorId(instructorId).Reverse();

            ClassDataService classDataService = new ClassDataService(dbContext);
            var c = classDataService.GetClassById(classId);
            ViewData["ClassName"] = c.Name;
            ViewData["ClassId"] = c.Id;

            return View(assignments);
        }

        public async Task<IActionResult> AddSelectedAssignment(int classId, int assignmentId)
        {
            AssignmentDataService assignmentDataService = new AssignmentDataService(dbContext);
            var assignment = assignmentDataService.GetAssignmentById(assignmentId);

            var newAssignment = new Assignment
            {
                Submissions = new List<Submission>(),

                Name = assignment.Name,
                StartDate = assignment.StartDate,
                EndDate = assignment.EndDate,
                Description = assignment.Description,
                MemoryLimit = assignment.MemoryLimit,
                TimeLimit = assignment.TimeLimit,
                Languages = assignment.Languages,
                ClassId = classId,
            };

            assignmentDataService.AddAssignment(newAssignment);

            foreach (var test in assignment.TestCases)
            {
                var testCase = new TestCaseSpecification(test);
                testCase.AssignmentId = newAssignment.Id;

                newAssignment.TestCases.Add(testCase);
            }

            ClassDataService classDataService = new ClassDataService(dbContext);
            var c = classDataService.GetClassById(classId);
            c.Assignments.Add(newAssignment);

            await dbContext.SaveChangesAsync();

            return RedirectToAction("Index", "Home");
        }

        public IActionResult InstructorAssignmentDetails(int id)
        {
            AssignmentDataService assignmentDataService = new AssignmentDataService(dbContext);
            var assignment = assignmentDataService.GetAssignmentById(id);

            return View(assignment);
        }

        public IActionResult StudentAssignmentDetails(int id)
        {
            AssignmentDataService assignmentDataService = new AssignmentDataService(dbContext);
            Assignment assignment = assignmentDataService.GetAssignmentById(id);

            return View(assignment);
        }

        public IActionResult EditAssignment(int id)
        {
            AssignmentDataService assignmentDataService = new AssignmentDataService(dbContext);
            Assignment assignment = assignmentDataService.GetAssignmentById(id);

            EditAssignmentViewModel model = new EditAssignmentViewModel()
            {
                ClassId = assignment.ClassId,
                Description = assignment.Description,
                EndDate = assignment.EndDate,
                StartDate = assignment.StartDate,
                Languages = assignment.Languages,
                MemoryLimit = assignment.MemoryLimit,
                TimeLimit = assignment.TimeLimit,
                Name = assignment.Name,
                NumberOfTestCases = assignment.TestCases.Count,
                TestCases = assignment.TestCases
            };

            ViewData["AssignmentId"] = assignment.Id;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditAssignment(EditAssignmentViewModel model, int assignmentId)
        {

            AssignmentDataService assignmentDataService = new AssignmentDataService(dbContext);
            Assignment assignment = assignmentDataService.GetAssignmentById(assignmentId);
            assignmentDataService.UpdateAssignment(model, assignment);

            await dbContext.SaveChangesAsync();

            return RedirectToAction("Details", "Instructor", new { id = assignment.ClassId});
        }

        public async Task<ActionResult> DeleteAssignment(int assignmentId)
        {
            AssignmentDataService assignmentDataService = new AssignmentDataService(dbContext);
            Assignment assignment = assignmentDataService.GetAssignmentById(assignmentId);

            assignmentDataService.DeleteAssignment(assignment);
            await dbContext.SaveChangesAsync();

            return RedirectToAction("Details", "Instructor", new { id = assignment.ClassId });
        }

        public IActionResult ViewAssignments(int classId)
        {
            AssignmentDataService assignmentDataService = new AssignmentDataService(dbContext);
            IEnumerable<Assignment> assignments = assignmentDataService.GetAssignmentsByClassId(classId).Reverse();

            StudentDataService studentDataService = new StudentDataService(dbContext);
            student = studentDataService.GetStudentByUsername(UserManager.GetUserName(User));

            ViewData.Add("StudentId", student.Id);

            return View(assignments);
        }

        public IActionResult SubmitToAssignment(int Id, int studentId)
        {
            AssignmentDataService assignmentDataService = new AssignmentDataService(dbContext);

            Assignment assignment = assignmentDataService.GetAssignmentById(Id);

            SubmissionInputViewModel model = new SubmissionInputViewModel
            {
                AssignmentId = Id,
                Language = assignment.Languages[0],
                UserId = studentId,
                ClassId = assignment.ClassId
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> SubmitToAssignment(SubmissionInputViewModel input)
        {
            StudentDataService studentDataService = new StudentDataService(dbContext);
            Student student = studentDataService.GetStudentById(input.UserId);

            bool hasAccess = false;

            foreach(StudentClass studentClass in student.StudentClasses)
            {
                if(studentClass.ClassId == input.ClassId)
                {
                    hasAccess = true;
                }
            }

            if (ModelState.IsValid && hasAccess)
            {
                Submission submission = new Submission();

                submission.Input.SourceCode = input.SourceCode;
                submission.Input.Language = input.Language;
                submission.AssignmentId = input.AssignmentId;
                submission.UserId = input.UserId;
                submission.SubmissionTime = DateTime.Now;

                SubmissionDataService submissionService = new SubmissionDataService(dbContext);
                submissionService.AddSubmission(submission);
                await dbContext.SaveChangesAsync(); // SubmissionId now set on local submission


                AssignmentDataService assignmentDataService = new AssignmentDataService(dbContext);
                Assignment assignment = assignmentDataService.GetAssignmentById(submission.AssignmentId);

                assignment.Submissions.Add(submission);

                GraderMethod.GradeSubmission(submission, dbContext);
                submission.Output.Runtime = assignment.TimeLimit;

                if (submission.Compile())
                {
                    submission.RunAndCompare();
                    submission.GradeTestCases();
                    submission.MaxRunTime();
                }

                dbContext.Submissions.Update(submission);
                dbContext.Assignments.Update(assignment);

                await dbContext.SaveChangesAsync();

                submission.deleteJunkFiles();

                return RedirectToAction("SubmissionDetails", "Submission", new { id = submission.SubmissionId });
            }

            return RedirectToAction("UnAuthorized", "Home");
        }

        public IActionResult GradesByAssignment(int id)
        {

AutoGrader/AutoGrader/Views/Shared/AssignmentDetails.cshtml
@model AutoGrader.Models.Assignment.Assignment

@{
    ViewData["Title"] = "Assignment Details: " + Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Assignment Details: @Model.Name</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Start Date
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt>
            End Date
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            Memory Limit
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MemoryLimit) kb
        </dd>
        <dt>
            Time Limit
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeLimit) ms
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Languages)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Languages)
        </dd>
    </dl>
</div>

AutoGrader/AutoGrader/Views/Shared/ViewAllSubmissions.cshtml
@model IEnumerable<AutoGrader.Models.Submission.Submission>

@{
    ViewData["Title"] = "Submissions for " + ViewData["StudentName"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Submissions for @ViewData["StudentName"]</h2>
<br />
<h4>Assignment: @ViewData["AssignmentName"]</h4>

@if (Model.Count() != 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    Submission ID
                </th>
                <th>
                    Submission Time
                </th>
                <th>
                    Grade
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.SubmissionId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SubmissionTime)
                    </td>
                    <td>
                        @{
                            var grade = item.Grade * 100;
                        }
                        @grade%
                    </td>
                    <td>
                        <a asp-controller="Assignment" asp-action="SubmissionDetails" asp-route-id="@item.SubmissionId">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <br />
    <h4 class="danger">No submissions on this assignment.</h4>
}

AutoGrader/AutoGrader/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoGrader</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AutoGrader</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   @* <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>*@
                    @*<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>*@
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    @*<partial name="_CookieConsentPartial" />*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - AutoGrader</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>