AutoGrader/AutoGrader/Models/Submission/Submission.cs
using System;

namespace AutoGrader.Models.Submission
{
    public class Submission
    {
        public Submission() 
        {
            Input = new SubmissionInput();
            Output = new SubmissionOutput();
            Grade = 0;
        }

        public int SubmissionId { get; set; }

        public int UserId { get; set; }

        public int AssignmentId { get; set; }

        public double Grade { get; set; }

        public DateTime SubmissionTime { get; set; }

        public SubmissionInput Input { get; set; }

        public SubmissionOutput Output { get; set; }
    }
}

AutoGrader/AutoGrader/Models/Submission/SubmissionInput.cs
  namespace AutoGrader.Models.Submission
{
    public class SubmissionInput
    {
        public SubmissionInput()
        {
        }

        public int Id { get; set; }

        public string SourceCode { get; set; }

        public string Language { get; set; }
    }
}

AutoGrader/AutoGrader/Models/Submission/SubmissionOutput.cs
using System.Collections.Generic;

namespace AutoGrader.Models.Submission
{
    public class SubmissionOutput
    {
        public SubmissionOutput()
        {
            Runtime = -1.0;
            TestCases = new List<TestCaseReport>();
        }

        public int Id { get; set; }

        public bool Compiled { get; set; }

        public double Runtime { get; set; }

        public string CompileOutput { get; set; }

        public int MemoryLimit { get; set; }

        public List<TestCaseReport> TestCases { get; set; }
    }
}

AutoGrader/AutoGrader/Models/Submission/SubmissionReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoGrader.Models.Submission
{
    public class SubmissionReport
    {
        public SubmissionReport()
        {
            Comments = new List<string>();
        }

        public int UserId { get; set; }

        public int SubmissionId { get; set; }

        public int ReportId { get; set; }

        public int AssignmentId { get; set; }

        public DateTime SubmissionTime { get; set; }

        public int ExecutionTime { get; set; }

        public string SourceCodeFileName { get; set; }

        public bool[] TestCases { get; set; }

        public List<string> Comments { get; set; }

        public string Language { get; set; }
    }
}

AutoGrader/AutoGrader/Models/Submission/TestCase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoGrader.Models.TestCaseReport
{
    public class TestCase
    {
        public TestCase()
        {
        }

        public bool PassFail { get; set; }

         public string CodeOutput { get; set; }

        public string Feedback { get; set; }

        public int Runtime { get; set; }
    }
}

AutoGrader/AutoGrader/Models/Submission/TestCaseReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoGrader.Models.Submission
{
    public class TestCaseReport
    {
        public TestCaseReport()
        {
            
        }

        public int Id { get; set; }

        public bool Pass { get; set; }

        public string CodeInput { get; set; }

        public string CodeOutput { get; set; }

        public string ExpectedOutput { get; set; }

        public string Feedback { get; set; }

        public int Runtime { get; set; }
    }
}

AutoGrader/AutoGrader/Controllers/SubmissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoGrader.DataAccess;
using AutoGrader.Models.Submission;
using Microsoft.AspNetCore.Mvc;

namespace AutoGrader.Controllers
{
    public class SubmissionController : Controller
    {
        private AutoGraderDbContext dbContext;

        public SubmissionController(AutoGraderDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IActionResult ViewAllSubmissionsOnAssignment(int assignmentId, int studentId)
        {
            AssignmentDataService assignmentDataService = new AssignmentDataService(dbContext);
            IEnumerable<Submission> submissions = assignmentDataService.GetStudentSubmissionsOnAssignment(studentId, assignmentId).Reverse();
            var assignmentName = assignmentDataService.GetAssignmentById(assignmentId).Name;
            ViewData["AssignmentName"] = assignmentName;

            StudentDataService studentDataService = new StudentDataService(dbContext);
            var student = studentDataService.GetStudentById(studentId);
            var name = student.FirstName + " " + student.LastName;
            ViewData["StudentName"] = name;

            return View(submissions);
        }

        public IActionResult SubmissionDetails(int id)
        {
            SubmissionDataService submissionDataService = new SubmissionDataService(dbContext);
            var submission = submissionDataService.GetSubmissionById(id);

            AssignmentDataService assignmentDataService = new AssignmentDataService(dbContext);
            ViewData["AssignmentName"] = assignmentDataService.GetAssignmentById(submission.AssignmentId).Name;

            return View(submission);
        }
    }
}

AutoGrader/AutoGrader/Views/Submission/SubmissionDetails.cshtml
@model AutoGrader.Models.Submission.Submission

@{
    ViewData["Title"] = "Submission Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Submission Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Assignment Name
        </dt>
        <dd>
            @ViewData["Assignmentname"]
        </dd>
        <dt>
            Submission ID
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubmissionId)
        </dd>
        <dt>
            Submission Time
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubmissionTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd>
            @{
                var grade = Model.Grade * 100;
            }
            @grade%
        </dd>
        <dt>
            Compiled
        </dt>
        <dd>
            @Model.Output.Compiled.ToString()
        </dd>
        <dt>
            Runtime
        </dt>
        <dd>
            @{
                string text;
                if (Model.Output.Runtime == -1)
                {
                    text = "Code did not compile.";
                }
                else
                {
                    text = Model.Output.Runtime + " ms";
                }
            }
            @text
        </dd>
    </dl>
</div>
<br />
<div>
    <dl class="dl-horizontal">
        @{
            int i = 1;
            foreach (var test in Model.Output.TestCases)
            {
                @if (test.Pass)
                {
                    text = "Pass";
                }
                else
                {
                    text = "Fail | Feedback: " + test.Feedback;
                }

                <dt>
                    Test Case @i:
                </dt>
                <dd>
                    @text
                </dd>
                i++;
            }
        }
    </dl>
</div>

@if (Model.Output.CompileOutput != "")
{
    <h4>Compiler Output</h4>
    <div>
        <textarea draggable="false" readonly="readonly" rows="8" style="width:100%; resize:none;">@Model.Output.CompileOutput</textarea>
    </div>
}
<h4>Source Code (@Model.Input.Language)</h4>
<div>
    <textarea draggable="false" readonly="readonly" rows="15" style="width:100%; resize:none; font-family: 'Courier New'">@Model.Input.SourceCode</textarea>
</div>

AutoGrader/AutoGrader/Views/Submission/ViewAllSubmissionsOnAssignment.cshtml
@model IEnumerable<AutoGrader.Models.Submission.Submission>

@{
    ViewData["Title"] = "Submissions for " + ViewData["StudentName"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Submissions for @ViewData["StudentName"]</h2>
<br />
<h4>Assignment: @ViewData["AssignmentName"]</h4>

@if (Model.Count() != 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    Submission ID
                </th>
                <th>
                    Submission Time
                </th>
                <th>
                    Grade
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.SubmissionId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SubmissionTime)
                    </td>
                    <td>
                        @{
                            var grade = item.Grade * 100;
                        }
                        @grade%
                    </td>
                    <td>
                        <a asp-controller="Submission" asp-action="SubmissionDetails" asp-route-id="@item.SubmissionId">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <br />
    <h4 class="danger">No submissions on this assignment.</h4>
}